import '../models/job.dart';

class JobService {
  static List<Job> getCuratedLiveJobs() {
    return [
      // 1. Manufacturing (製造加工)
      Job(
        id: 'job_mfg_1',
        category: JobCategory.manufacturing,
        sourceName: 'VietnamWorks 連線',
        sourceUrl: 'https://www.vietnamworks.com/viec-lam/tan-binh-garment',
        taxCode: '0301984712',
        companyNameZh: '新平工業區成衣外銷大廠 (胡志明市)',
        companyNameVi: 'CP Dệt May Xuất Khẩu Tân Bình (TP.HCM)',
        logoUrl: 'https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=120',
        titleZh: '成衣車縫熟手 (平車/拷克/雙針)',
        titleVi: 'Thợ May Công Nghiệp 1 Kim / Vắt Sổ',
        salaryMin: 8500000,
        salaryMax: 13000000,
        baseSalary: '6.0M (投保底薪)',
        allowance: '+2.5M (伙食+全勤700k)',
        overtimeRate: '1.5x (冷氣車間)',
        amenitiesZh: ['✓ 供中餐', '✓ 全勤獎金700k', '✓ 第13個月年終', '✓ 完整勞健保'],
        amenitiesVi: ['✓ Bao ăn trưa', '✓ Thưởng chuyên cần 700k', '✓ Tháng 13', '✓ Đầy đủ BHXH'],
        latitude: 10.8120,
        longitude: 106.6280,
        industrialZone: 'KCN Tân Bình, TP.HCM',
        commuteDistance: '4.8 km',
        commuteTime: '~12 分鐘機車',
        overallRating: 4.7,
        reviewCount: 114,
        onTimeSalaryRate: 99,
        reviews: [
          CompanyReview(authorName: 'Nguyễn T. Lan', authorRole: 'Tổ may 3', rating: 5.0, comment: 'Xưởng có máy lạnh mát mẻ, phát lương đúng ngày 10 hàng tháng, cơm trưa ngon.', date: '2026-08-15'),
          CompanyReview(authorName: 'Trần Văn Tùng', authorRole: 'KCS', rating: 4.5, comment: 'Tăng ca có phụ cấp rõ ràng, tổ trưởng hỗ trợ nhiệt tình.', date: '2026-08-02'),
        ],
        zaloUrl: 'https://zalo.me/g/tanbinh_garment',
        facebookUrl: 'https://facebook.com/kcntanbinh.tuyendung',
        hotline: '0283815xxxx',
        candidateName: '陳氏梅 (Trần Thị Mai)',
        candidateAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=120',
        candidateStabilityScore: 91,
        candidateAvgTenure: '1.9 年 (近兩年零跳槽)',
        candidateSkills: '平車5年、拷克熟手、成衣包裝',
        candidateWorkHistory: '同奈 Amata 成衣廠 (2年) • 新平車縫組 (1.8年)',
      ),

      // 2. Logistics & Warehousing (倉儲物流)
      Job(
        id: 'job_log_1',
        category: JobCategory.logistics,
        sourceName: 'TopCV 連線',
        sourceUrl: 'https://www.topcv.vn/viec-lam/vsip-logistics',
        taxCode: '3702849102',
        companyNameZh: '平陽 VSIP 1 國際物流倉儲大廠 (外資大廠)',
        companyNameVi: 'Tập Đoàn Logistics & Kho Vận VSIP 1',
        logoUrl: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=120',
        titleZh: '堆高機司機兼倉儲理貨組長',
        titleVi: 'Tài xế Lái Xe Nâng & Trưởng Nhóm Kho',
        salaryMin: 11000000,
        salaryMax: 15500000,
        baseSalary: '7.5M (投保底薪)',
        allowance: '+3.5M (伙食+夜點+全勤)',
        overtimeRate: '1.5x~2.0x (冷氣無塵倉)',
        amenitiesZh: ['✓ 包午晚2餐', '✓ 免費冷氣宿舍', '✓ 交通車接送', '✓ 完整勞健保'],
        amenitiesVi: ['✓ Bao cơm 2 bữa', '✓ KTX máy lạnh miễn phí', '✓ Xe đưa rước', '✓ Đầy đủ BHXH'],
        latitude: 10.9315,
        longitude: 106.6980,
        industrialZone: 'KCN VSIP 1, Bình Dương',
        commuteDistance: '2.3 km',
        commuteTime: '~6 分鐘機車',
        overallRating: 4.9,
        reviewCount: 68,
        onTimeSalaryRate: 100,
        reviews: [
          CompanyReview(authorName: 'Lê Hoàng Nam', authorRole: 'Lái xe nâng', rating: 5.0, comment: 'Ký túc xá máy lạnh sạch như khách sạn, xe nâng điện đời mới dễ lái.', date: '2026-08-20'),
          CompanyReview(authorName: 'Đặng Quốc Huy', authorRole: 'Thủ kho', rating: 4.8, comment: 'Lương thưởng minh bạch, đóng bảo hiểm đầy đủ trên lương thực tế.', date: '2026-08-10'),
        ],
        zaloUrl: 'https://zalo.me/g/vsip_tuyendung',
        facebookUrl: 'https://facebook.com/groups/kcn.binhduong.job',
        hotline: '0274382xxxx',
        candidateName: '阮文雄 (Nguyễn Văn Hùng)',
        candidateAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120',
        candidateStabilityScore: 96,
        candidateAvgTenure: '2.1 年 (極高穩定度)',
        candidateSkills: '堆高機安全操作證、倉儲ERP、基礎華語',
        candidateWorkHistory: '神浪物流中心 (2年3個月) • VSIP 1 倉儲 (2年)',
      ),

      // 3. F&B & Dining (餐飲服務)
      Job(
        id: 'job_fnb_1',
        category: JobCategory.fnb,
        sourceName: 'CareerViet 連線',
        sourceUrl: 'https://careerviet.vn/saigon-heritage-cafe',
        taxCode: '0318273645',
        companyNameZh: '西貢 Heritage 連鎖餐飲咖啡 (第一郡旗艦店)',
        companyNameVi: 'Chuỗi F&B Saigon Heritage (Quận 1)',
        logoUrl: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=120',
        titleZh: '門市調飲組長兼吧台主管 (輪班制)',
        titleVi: 'Trưởng Ca Pha Chế & Quản Lý Barista',
        salaryMin: 8000000,
        salaryMax: 11000000,
        baseSalary: '6.2M (底薪)',
        allowance: '+1.8M (週小費+交通補貼)',
        overtimeRate: '業績達標分紅 + 飲品半價',
        amenitiesZh: ['✓ 每日免費咖啡', '✓ 免費機車停車', '✓ 週發現金小費', '✓ 晉升店長考核'],
        amenitiesVi: ['✓ Đồ uống free', '✓ Gửi xe miễn phí', '✓ Chia tips tuần', '✓ Lộ trình lên Cửa hàng trưởng'],
        latitude: 10.7825,
        longitude: 106.6992,
        industrialZone: 'Quận 1, TP.HCM',
        commuteDistance: '7.1 km',
        commuteTime: '~18 分鐘機車',
        overallRating: 4.6,
        reviewCount: 86,
        onTimeSalaryRate: 98,
        reviews: [
          CompanyReview(authorName: 'Vũ Thảo My', authorRole: 'Barista', rating: 4.8, comment: 'Tips chia đều sòng phẳng mỗi tuần, môi trường năng động vui vẻ.', date: '2026-08-18'),
        ],
        zaloUrl: 'https://zalo.me/g/saigon_fnb_jobs',
        facebookUrl: 'https://facebook.com/saigonheritage.careers',
        hotline: '0283925xxxx',
        candidateName: '范氏芳 (Phạm Thị Phương)',
        candidateAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=120',
        candidateStabilityScore: 86,
        candidateAvgTenure: '1.5 年 (服務熱誠)',
        candidateSkills: 'Barista 中級證照、POS 收銀、英語日常溝通',
        candidateWorkHistory: 'Highlands Coffee (1.5年) • Phúc Long Barista (1年)',
      ),

      // 4. Precision Mechanics (機械精密加工)
      Job(
        id: 'job_mfg_2',
        category: JobCategory.manufacturing,
        sourceName: 'Việc Làm 24h & FB Group 連線',
        sourceUrl: 'https://vieclam24h.vn/co-khi-song-than-2',
        taxCode: '3709182314',
        companyNameZh: '神浪 2 工業區精密機械加工廠 (平陽省)',
        companyNameVi: 'Cơ Khí Chính Xác Sóng Thần 2 (Bình Dương)',
        logoUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=120',
        titleZh: 'CNC 車床銑床操作員 / TIG氬焊工',
        titleVi: 'Kỹ Thuật Viên Hàn TIG/MIG & Vận Hành CNC',
        salaryMin: 12000000,
        salaryMax: 17000000,
        baseSalary: '8.5M (投保底薪)',
        allowance: '+3.5M (伙食+技術加給)',
        overtimeRate: '1.5x~2.0x (夜班加成)',
        amenitiesZh: ['✓ 包早午2餐', '✓ 租屋補貼', '✓ 生產激勵獎金', '✓ 每年調薪考核'],
        amenitiesVi: ['✓ Bao ăn 2 bữa', '✓ Phụ cấp nhà trọ', '✓ Thưởng nóng', '✓ Tăng lương định kỳ'],
        latitude: 10.9050,
        longitude: 106.7450,
        industrialZone: 'KCN Sóng Thần 2, Dĩ An',
        commuteDistance: '3.9 km',
        commuteTime: '~9 分鐘機車',
        overallRating: 4.8,
        reviewCount: 52,
        onTimeSalaryRate: 99,
        reviews: [
          CompanyReview(authorName: 'Đỗ Minh Tuấn', authorRole: 'Thợ CNC', rating: 5.0, comment: 'Máy móc nhập khẩu hiện đại, trả tiền tăng ca đầy đủ đúng luật.', date: '2026-08-12'),
        ],
        zaloUrl: 'https://zalo.me/g/songthan2_cnc',
        facebookUrl: 'https://facebook.com/groups/cokhibinhduong',
        hotline: '0274379xxxx',
        candidateName: '黎文南 (Lê Văn Nam)',
        candidateAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120',
        candidateStabilityScore: 88,
        candidateAvgTenure: '1.7 年 (技術專精)',
        candidateSkills: 'CNC 車銑床、TIG 氬焊證、看工程圖',
        candidateWorkHistory: '平陽富士機械 (2年) • 神浪精密零件 (1.5年)',
      ),
    ];
  }
}
